version: '3'

services:
  app:
    image: rsilvy06/yselling-back:main
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "90:80"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.rule=Host(`laravel.silvy-leligois.fr`)"
      - "traefik.http.routers.dashy.entrypoints=websecure"
      - "traefik.http.routers.dashy.tls.certresolver=leresolver"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      # Add other Laravel environment variables here
    networks:
      - traefik

  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db_data:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    volumes:
      - meilisearch_data:/data.ms

  npm:
    image: node:latest
    container_name: npm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "install"]

networks:
  traefik:
    external: true

volumes:
  db_data:
  meilisearch_data:
