name: Publish Docker Image

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker-compose -f docker-compose.prod.yaml build

      - name: Push the Docker image
        run: docker-compose -f docker-compose.prod.yaml push
